const fs = require('fs')
const yaml = require('js-yaml')

var parse = `[
			{"id":"234430","name":"Kotetsu","icon":"ability_22.png","effects":[{"effect":{"break":{"def":65},"turns":1,"area":"AOE","target":"ENEMY"},"desc":"Reduce DEF by 65% for one turn to all enemies"},{"effect":{"damage":{"mecanism":"physical","damageType":"body","coef":6,"elements":["ice"]},"area":"AOE","target":"ENEMY"},"desc":"Physical ice damage (6x, ATK) to all enemies"}],"frames":[42],"move":"none","type":"ability","mpCost":36,"rarity":5,"level":13},
			{"id":"234431","name":"Self-Haste","icon":"ability_78.png","effects":[{"effect":null,"desc":"Increase the limit burst gauge fill rate by 150% for 3 turns to caster"},{"effect":{"lbFill":{"min":5,"max":5},"area":"SELF","target":"SELF"},"desc":"Increase LB gauge by 5 to caster"},{"effect":{"noUse":true,"area":"SELF","target":"SELF"},"desc":"Use Self-Haste (511680) next turn on caster"},{"effect":{"noUse":true,"area":"SELF","target":"SELF"},"desc":"Use Self-Haste (511681) after a 2 turn delay on caster"}],"type":"ability","mpCost":24,"rarity":5,"level":20},
			{"id":"206980","name":"Defensive Barrier","icon":"ability_43.png","effects":[{"effect":{"noUse":true,"globalMitigation":20,"turns":3,"area":"AOE","target":"ALLY"},"desc":"Reduce damage taken by 20% to all allies for 3 turns"}],"type":"ability","mpCost":24,"rarity":5,"level":20},
			{"id":"234432","name":"Healing Aura","icon":"ability_4.png","effects":[{"effect":{"noUse":true,"area":"AOE","target":"ALLY"},"desc":"Restore 4000 HP and 50 MP to all allies"}],"type":"ability","mpCost":48,"rarity":5,"level":44},
			{"id":"511688","name":"Armor of Discontinuity","icon":"ability_77.png","effects":[{"effect":{"noUse":true,"area":"SELF","target":"SELF"},"desc":"Grant a 1000 HP shield to caster for 9999 turns"}],"type":"ability","unlockedBy":["234444"]},
			{"id":"234433","name":"Osmose Force","icon":"ability_6.png","effects":[{"effect":null,"desc":"Magic damage (0.3x, MAG) as MP drain (10%) to all enemies"}],"type":"ability","mpCost":28,"rarity":5,"level":67},
			{"id":"234435","name":"Frost Blade","icon":"ability_22.png","effects":[{"effect":{"damage":{"mecanism":"magical","damageType":"mind","coef":12,"elements":["ice"]},"area":"AOE","target":"ENEMY"},"desc":"Magic ice damage (12x, MAG) to all enemies"},{"effect":{"imperil":{"ice":120},"turns":3,"area":"AOE","target":"ENEMY"},"desc":"Reduce resistance to Ice by 120% for 3 turns to all enemies"}],"frames":[42,62,82,102,122,142,162,182],"chainFamily":"CWA","move":"none","type":"ability","mpCost":54,"rarity":6,"level":22},
			{"id":"234436","name":"Final Hour","icon":"ability_63.png","effects":[{"effect":{"statsBuff":{"mag":150},"turns":3,"area":"AOE","target":"ALLY"},"desc":"Increase MAG by 150% for 3 turns to all allies"},{"effect":{"resist":[{"name":"ice","percent":60}],"turns":3,"area":"AOE","target":"ALLY"},"desc":"Increase resistance to Ice by 60% for 3 turns to all allies"}],"type":"ability","mpCost":60,"rarity":6,"level":44},
			{"id":"234437","name":"Hamon","icon":"ability_22.png","effects":[{"effect":{"damage":{"mecanism":"magical","damageType":"mind","coef":15,"elements":["ice"]},"area":"ST","target":"ENEMY"},"desc":"Magic ice damage (15x, MAG) to one enemy"},{"effect":{"break":{"atk":70},"turns":3,"area":"ST","target":"ENEMY"},"desc":"Reduce ATK by 70% for 3 turns to one enemy"}],"frames":[80],"move":"none","type":"ability","mpCost":52,"rarity":6,"level":80},
			{"id":"234434","name":"Frozen Flash","icon":"ability_22.png","effects":[{"effect":{"damage":{"mecanism":"physical","damageType":"body","coef":0.5,"ignore":{"def":50},"elements":["ice"]},"area":"ST","target":"ENEMY"},"desc":"Physical ice damage (0.5x * 2 = 1x, ATK) to one enemy (ignore cover)"},{"effect":{"damage":{"mecanism":"physical","damageType":"body","coef":5.5,"ignore":{"def":50},"elements":["ice"]},"area":"ST","target":"ENEMY"},"desc":"Physical ice damage (5.5x * 2 = 11x, ATK) to one enemy (ignore cover)"},{"effect":{"imperil":{"ice":120},"turns":3,"area":"ST","target":"ENEMY"},"desc":"Reduce resistance to Ice by 120% for 3 turns to one enemy"}],"frames":[70,76,82,88,94,100,106,112],"chainFamily":"AMoE","move":"none","type":"ability","mpCost":54,"rarity":6,"level":80},
			{"id":"511682","name":"Double Steel Wings","icon":"ability_8.png","effects":[{"effect":{"multicast":{"time":2,"type":"skills","skills":[{"id":"234430","name":"Kotetsu"},{"id":"234431","name":"Self-Haste"},{"id":"234432","name":"Healing Aura"},{"id":"234433","name":"Osmose Force"},{"id":"234434","name":"Frozen Flash"},{"id":"234435","name":"Frost Blade"},{"id":"234436","name":"Final Hour"},{"id":"234437","name":"Hamon"},{"id":"234439","name":"Transcendent Wings"},{"id":"234440","name":"Excalibur - Shining Blade"},{"id":"234441","name":"Excalibur - Gleaming Blade"},{"id":"234442","name":"Quicken"},{"id":"206980","name":"Defensive Barrier"}]}},"desc":"Gain 2 uses of Defensive Barrier (206980), Excalibur - Gleaming Blade (234441), Excalibur - Shining Blade (234440), Final Hour (234436), Frost Blade (234435), Frozen Flash (234434), Hamon (234437), Healing Aura (234432), Kotetsu (234430), Osmose Force (234433), Quicken (234442), Self-Haste (234431) and Transcendent Wings (234439) for one turn"}],"type":"ability"},
			{"name":"Triple Steel Wings","icon":"ability_8.png","effects":[{"effect":{"multicast":{"time":3,"type":"skills","skills":[{"id":"234430","name":"Kotetsu"},{"id":"234431","name":"Self-Haste"},{"id":"234432","name":"Healing Aura"},{"id":"234433","name":"Osmose Force"},{"id":"234434","name":"Frozen Flash"},{"id":"234435","name":"Frost Blade"},{"id":"234436","name":"Final Hour"},{"id":"234437","name":"Hamon"},{"id":"234439","name":"Transcendent Wings"},{"id":"234440","name":"Excalibur - Shining Blade"},{"id":"234441","name":"Excalibur - Gleaming Blade"},{"id":"234442","name":"Quicken"},{"id":"206980","name":"Defensive Barrier"}]}},"desc":"Enable unit to use Kotetsu(234430), Self-Haste(234431), Healing Aura(234432), Osmose Force(234433), Frozen Flash(234434), Frost Blade(234435), Final Hour(234436), Hamon(234437), Transcendent Wings(234439), Excalibur - Shining Blade(234440), Excalibur - Gleaming Blade(234441), Quicken(234442), Defensive Barrier(206980) 3 times in one turn"}],"id":"unlocked-641937790","unlockedBy":["511683"]},
			{"id":"234439","name":"Transcendent Wings","icon":"ability_105.png","effects":[{"effect":{"cooldownSkill":{"id":"511683","name":"Transcendent Wings","icon":"ability_105.png","effects":[{"effect":{"resist":[{"name":"ice","percent":80}],"turns":5,"area":"AOE","target":"ALLY"},"desc":"Increase resistance to Ice by 80% for 5 turns to all allies"},{"effect":{"lbFill":{"min":56,"max":56},"area":"SELF","target":"SELF"},"desc":"Increase LB gauge by 56 to caster"},{"effect":{"skillEnhancement":{"234434":4.75},"turn":5},"desc":"Increase damage of Frozen Flash (234434) by 475% for 5 turns"},{"effect":{"skillEnhancement":{"511685":4,"511686":4},"turn":5},"desc":"Increase damage of Excalibur skills  [Gleaming Blade (511686) / Shining Blade (511685)] by 400% for 5 turns"},{"effect":{"gainSkills":{"turns":5,"skills":[{"id":"unlocked-641937790","name":"Triple Steel Wings"}]}},"desc":"Gain 3 uses of Defensive Barrier (206980), Excalibur - Gleaming Blade (234441), Excalibur - Shining Blade (234440), Final Hour (234436), Frost Blade (234435), Frozen Flash (234434), Hamon (234437), Healing Aura (234432), Kotetsu (234430), Osmose Force (234433), Quicken (234442), Self-Haste (234431) and Transcendent Wings (234439) for 5 turns"}],"type":"ability","mpCost":99},"cooldownTurns":6,"startTurn":1,"area":"AOE","target":"ALLY"},"desc":"Unlock Transcendent Wings (511683) on turn 1 [6 turns CD]"}],"type":"ability","mpCost":99,"rarity":7,"level":101},
			{"id":"511691","name":"Mystic Dash","icon":"ability_63.png","effects":[{"effect":{"statsBuff":{"atk":200,"mag":200},"turns":9999,"area":"SELF","target":"SELF"},"desc":"Increase ATK and MAG by 200% for 9999 turns to caster"},{"effect":{"lbFill":{"min":5,"max":10},"area":"SELF","target":"SELF"},"desc":"Increase LB gauge by 5-10 to caster"}],"type":"ability","unlockedBy":["234451"]},
			{"id":"234440","name":"Excalibur - Shining Blade","icon":"ability_105.png","effects":[{"effect":{"cooldownSkill":{"id":"511685","name":"Excalibur - Shining Blade","icon":"ability_105.png","effects":[{"effect":{"damage":{"mecanism":"physical","damageType":"body","coef":1.5,"ignore":{"def":50},"elements":["ice"]},"area":"ST","target":"ENEMY"},"desc":"Physical ice damage (1.5x * 2 = 3x, ATK) to one enemy (ignore cover)"},{"effect":{"damage":{"mecanism":"physical","damageType":"body","coef":12,"ignore":{"def":50},"elements":["ice"]},"area":"ST","target":"ENEMY"},"desc":"Physical ice damage (12x * 2 = 24x, ATK) to one enemy (ignore cover)"},{"effect":{"statsBuff":{"lbDamage":100},"turns":2,"area":"SELF","target":"SELF"},"desc":"Increase LB damage by 100% for 2 turns"}],"frames":[70,76,82,88,94,100,106,112],"chainFamily":"AMoE","move":"none","type":"ability","mpCost":99},"cooldownTurns":3,"startTurn":3,"area":"ST","target":"ENEMY"},"desc":"Unlock Excalibur - Shining Blade (511685) on turn 3 [3 turns CD]"}],"type":"ability","mpCost":99,"rarity":7,"level":105},
			{"id":"234441","name":"Excalibur - Gleaming Blade","icon":"ability_105.png","effects":[{"effect":{"cooldownSkill":{"id":"511686","name":"Excalibur - Gleaming Blade","icon":"ability_105.png","effects":[{"effect":{"damage":{"mecanism":"magical","damageType":"mind","coef":2.5,"ignore":{"spr":50},"elements":["ice"]},"area":"ST","target":"ENEMY"},"desc":"Magic ice damage (2.5x * 2 = 5x, MAG) to one enemy (ignore reflect)"},{"effect":{"damage":{"mecanism":"magical","damageType":"mind","coef":18,"ignore":{"spr":50},"elements":["ice"]},"area":"ST","target":"ENEMY"},"desc":"Magic ice damage (18x * 2 = 36x, MAG) to one enemy (ignore reflect)"},{"effect":{"statsBuff":{"lbDamage":100},"turns":2,"area":"SELF","target":"SELF"},"desc":"Increase LB damage by 100% for 2 turns"}],"frames":[42,62,82,102,122,142,162,182],"chainFamily":"CWA","move":"none","type":"ability","mpCost":99},"cooldownTurns":3,"startTurn":3,"area":"ST","target":"ENEMY"},"desc":"Unlock Excalibur - Gleaming Blade (511686) on turn 3 [3 turns CD]"}],"type":"ability","mpCost":99,"rarity":7,"level":105},
			{"id":"234442","name":"Quicken","icon":"ability_105.png","effects":[{"effect":{"cooldownSkill":{"id":"511687","name":"Quicken","icon":"ability_105.png","effects":[{"effect":{"statsBuff":{},"turns":0,"area":"ST","target":"ALLY"},"desc":"No effect"},{"effect":{"lbFill":{"min":1000,"max":1000},"area":"ST","target":"ALLY"},"desc":"Increase LB gauge by 1000 to one ally"}],"type":"ability","mpCost":255},"cooldownTurns":99,"startTurn":1,"area":"ST","target":"ALLY"},"desc":"Unlock Quicken (511687) on turn 1 [99 turns CD]"}],"type":"ability","mpCost":255,"rarity":7,"level":110}
]`


async function readYaml() {

  fs.writeFile('./unitsParse.yaml', yaml.safeDump(JSON.parse(parse)), (err) => { console.log(err) });

}

readYaml();